### ISSUE TITLE
Doesn't work if you don't use nest-winston

### ISSUE THREAD

**Issue by grimurd** [wisekaa03/nestjs-ldap#3]
This module has a hard dependency on nest-winston. It won't run unless you import nestjs winston in your app module. For those of us using different loggers that makes this module unusable without also installing nest-winston.

I suggest using the default nestjs logger instead. Anybody can replace the default logger with their own implementation.

**Comment by wisekaa03** [comment]
Ok i'll think about it. Default nestjs logger on 1 days.
